RAID = [
    "يا كسمك",
    "يا طري",
    "يا ابن المركوب",
    "يا بز",
    "يا حكاك",
    "يبن الزانيه",
    "يا عرصجي",
    "يبن القحبه",
    "يا لبوه",
    "يا ابن الحيحانه",
    "يا ابن الحيحانه",
    "يا شرموط",
    "يا كسختك",
    "يا ابن المتناكه",
    "يا ابن المتناكه",
    "يا ابن الشرموطه",
    "يا ابن القحبه",
    "يا ابن العرص",
    "يا خول",
    "FUCK OFF🤣",
    "FUCK YOU",
    "BITCH",
    "SUCK MY DICK RANDI",
    "FUCK YOUR SELF",
    "GIVE YOUR PUSSY🤣🤤💋",
    "COME WITH YOUR MOM🤤💋",
    "I'll FUCK YOU WITH YOUR MOM",
    "OHH YOUR MOM IS FAN OF MY DICK",
    "MF SPOTTED",
    "YOUR MOM PUSSY OP😍🤤💋",
    "YOUR MOM IS GETTING FUCKED BY ME HARD🤤💋",
    "YOUR MOM IS WITH ME AND🤤💋 SUCKING MY DICK",
    "YOUR MOM ASS BEST🤣",
    "YOUR MOM IS BLEEDING 😂",
    "TERI AMMY KE BHOXDE KO JALTE HUYE KOYLE PE SHEK KE PELUNGA - 🖤👅👌",
    "TERE BAAP KO BICH SADAK PE GIRA GIRA KR MARUNGA AUR LAST ME USKE MUH PE MOOT KAR JAUNGA 🤣🤣👌🖤",
    "BHAINS JAISI AMMY KE AULAAD SALE LODU JAISE SHAKAL KE 🤣🤣",
    "TERI BHEN KO USKE COLLEGE KE LIBRARY ME HI CHOD KE PREGNANT KARDUNGA LODU 👻🤣🤣🤣😈👅",
    "TERI BHEN KE MUH ME LODA DAL KE USSE PAPA BULWAUNGA KHUD KO 👅😈",
    "TERI BHEN KO JHULE PE BAITHA KE USKI CHUT PE APNA GARAM LODA TOUCH KARUNGA 🤣👻",
    "TERI AMMY KA ENC0UNTER KAR DUNGA PRIYANKA  READY KE BALAT KARIYON KI TARAH 🤣",
    "TERI AMMA KA BHOSDA MEI BULDOSER LEKE GHUS JAUNGA 😈🤣👀👅",
    "CHUP KAR RANDI PUTRA CHINNAL KE AULAAD 🤣",
    "TERI BHEN KE BHOSDE ME @Nobi_xxd KA LODA😂",
    "TERI MA TOH MERA KABJE MAI HAI LENE CHATA HAI TOH PAY 3 LAKH..🤩👊👤😍",
    "TERI BHEN KA BHOSDA 😂 TERI BHEN MARGAYI💥🔥🔥",
    "TERI MA KA BHOSDA ME @Nobi_xxd KA LODA😂🔥",
    "TERI BHEN MEREKO PAPA BOLTE HAI👿😎👊",
    "SAB LOG BOLTE FLASH PAPA  OP BOLTE 😈🤩🔥",
    "FLASH PAPA  PAPA 👅YE NAM YAD RAKHNA KID🤩",
    "FLASH PAPA  KA PIRO BOT SE CHOD JAYEGA LODE😂👿😳",
    "TEREKO APNA BHEN CHAIYE OK DEDUNGA PAR PAISA DENE PADEGA😈👅",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍",
    "TERE BAAP XAKKA MADARCHOD USKI MA KI BUR ME USKI GAND  MARVA DUNGA",
    "AUR 9 MAHINE TERI MA KI CHOOT SE FIR SE EK TERE JAISE SUAR PAIDA HOGA😹",
    "AAJ PARTY ME AANA MAT BHULNA RANDI KI AULAD! MUNNILALSAAALEE MADARCHOD TERI MA KO CHODDUUU 😍😛",
    "GANDU MERE SADKE PAIDA HUE KIDE TERI BHEN K BUR ME🗣️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗣𝗨𝗦𝗦𝗬 𝗖𝗛𝗔𝗧𝗨𝗡𝗚𝗔 𝗕𝗘𝗧𝗘😂🍑🍆🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗥𝗔𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗞𝗜 𝗠𝗔𝗡𝗔𝗚𝗘𝗥 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗞𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗟𝗢 𝗣𝗔𝗥 𝗣𝗔𝗜𝗦𝗘 𝗗𝗘𝗧𝗘 𝗝𝗔𝗔𝗡𝗔 🤣🔥🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗙𝗔𝗡 𝗛𝗔𝗜😍👻💋🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗞𝗘 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔𝗔𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣🔥",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗕 𝗣𝗔𝗣𝗔 𝗚𝗔𝗟𝗧𝗜 𝗛𝗢 𝗚𝗔𝗬𝗜 𝗠𝗔𝗔𝗙 𝗞𝗔𝗥𝗗𝗢😁🍑🍆👻",
    "𝗔𝗣𝗡𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗚𝗔𝗔𝗔𝗡𝗗 𝗗𝗘𝗗𝗢 🥺 𝗧𝗛𝗢𝗗𝗜 𝗗𝗘𝗥 𝗣𝗘𝗟 𝗞𝗘 𝗗𝗘𝗧𝗔 𝗛𝗨 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗛𝗔𝗥 𝗕𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 𝗟𝗢𝗗𝗘 🤤💋",
]


RRAID = [
    "يا كسمك",
    "يا طري",
    "يا ابن المركوب",
    "يا بز",
    "يا حكاك",
    "يبن الزانيه",
    "يا عرصجي",
    "يبن القحبه",
    "يا لبوه",
    "يا ابن الحيحانه",
    "يا ابن الحيحانه",
    "يا شرموط",
    "يا كسختك",
    "يا ابن المتناكه",
    "يا ابن المتناكه",
    "يا ابن الشرموطه",
    "يا ابن القحبه",
    "يا ابن العرص",
    "يا خول",
    "FUCK OFF🤣",
    "FUCK YOU",
    "BITCH",
    "SUCK MY DICK RANDI",
    "FUCK YOUR SELF",
    "GIVE YOUR PUSSY🤣🤤💋",
    "COME WITH YOUR MOM🤤💋",
    "I'll FUCK YOU WITH YOUR MOM",
    "OHH YOUR MOM IS FAN OF MY DICK",
    "MF SPOTTED",
    "YOUR MOM PUSSY OP😍🤤💋",
    "YOUR MOM IS GETTING FUCKED BY ME HARD🤤💋",
    "YOUR MOM IS WITH ME AND🤤💋 SUCKING MY DICK",
    "YOUR MOM ASS BEST🤣",
    "YOUR MOM IS BLEEDING 😂",
    "يا كسمك",
    "يا طري",
    "يا ابن المركوب",
    "يا بز",
    "يا حكاك",
    "يبن الزانيه",
    "يا عرصجي",
    "يبن القحبه",
    "يا لبوه",
    "يا ابن الحيحانه",
    "يا ابن الحيحانه",
    "يا شرموط",
    "يا كسختك",
    "يا ابن المتناكه",
    "يا ابن المتناكه",
    "يا ابن الشرموطه",
    "يا ابن القحبه",
    "يا ابن العرص",
    "يا خول",
    "FUCK OFF🤣",
    "FUCK YOU",
    "BITCH",
    "SUCK MY DICK RANDI",
    "FUCK YOUR SELF",
    "GIVE YOUR PUSSY🤣",
    "COME WITH YOUR MOM",
    "I'll FUCK YOU WITH YOUR MOM",
    "OHH YOUR MOM IS FAN OF MY DICK",
    "MF SPOTTED",
    "YOUR MOM IS WITH ME AND SUCKING MY DICK",
    "YOUR MOM ASS BEST🤣",
    "YOUR MOM IS BLEEDING 😂",
    "SU𝗔R KE PILLE TERI ᴍ𝗔𝗔Kᴏ S𝗔D𝗔K PR LIT𝗔KE 𝗖HᴏD DUᑎG𝗔 😂😆🤤",
    "𝗔𝗕E TERI ᴍ𝗔𝗔K𝗔 𝗕HᴏSD𝗔 ᴍ𝗔DER𝗖HᴏᴏD KR PILLE P𝗔P𝗔 SE L𝗔DEG𝗔 TU 😼😂🤤",
    "G𝗔LI G𝗔LI ᑎE SHᴏR HE TERI ᴍ𝗔𝗔 R𝗔ᑎDI 𝗖HᴏR HE 💋💋💦",
    "𝗔𝗕E TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏDU R𝗔ᑎDIKE PILLE KUTTE KE 𝗖HᴏDE 😂👻🔥",
    "TERI ᴍ𝗔𝗔Kᴏ 𝗔ISE 𝗖HᴏD𝗔 𝗔ISE 𝗖HᴏD𝗔 TERI ᴍ𝗔𝗔𝗔 𝗕ED PEHI ᴍUTH DI𝗔 💦💦💦💦",
    "TERI 𝗕EHEᑎ KE 𝗕HᴏSDE ᴍE 𝗔𝗔𝗔G L𝗔G𝗔DI𝗔 ᴍER𝗔 ᴍᴏT𝗔 LUᑎD D𝗔LKE 🔥🔥💦😆😆",
    "R𝗔ᑎDIKE 𝗕𝗔𝗖HHE TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏDU 𝗖H𝗔L ᑎIK𝗔L",
    "KITᑎ𝗔 𝗖HᴏDU TERI R𝗔ᑎDI ᴍ𝗔𝗔KI 𝗖HUTH 𝗔𝗕𝗕 𝗔PᑎI 𝗕EHEᑎ Kᴏ 𝗕HEJ 😆👻🤤",
    "TERI 𝗕EHEᑎ KᴏTᴏ 𝗖HᴏD 𝗖HᴏDKE PUR𝗔 F𝗔𝗔D DI𝗔 𝗖HUTH 𝗔𝗕𝗕 TERI GF Kᴏ 𝗕HEJ 😆💦🤤",
    "TERI GF Kᴏ ETᑎ𝗔 𝗖HᴏD𝗔 𝗕EHEᑎ KE LᴏDE TERI GF Tᴏ ᴍERI R𝗔ᑎDI 𝗕𝗔ᑎG𝗔YI 𝗔𝗕𝗕 𝗖H𝗔L TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏDT𝗔 FIRSE ♥️💦😆😆😆😆",
    "H𝗔RI H𝗔RI GH𝗔𝗔S ᴍE JHᴏPD𝗔 TERI ᴍ𝗔𝗔K𝗔 𝗕HᴏSD𝗔 🤣🤣💋💦",
    "𝗖H𝗔L TERE 𝗕𝗔𝗔P Kᴏ 𝗕HEJ TER𝗔 𝗕𝗔SK𝗔 ᑎHI HE P𝗔P𝗔 SE L𝗔DEG𝗔 TU",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE 𝗕ᴏᴍ𝗕 D𝗔LKE UD𝗔 DUᑎG𝗔 ᴍ𝗔𝗔KE L𝗔WDE",
    "TERI ᴍ𝗔𝗔Kᴏ TR𝗔Iᑎ ᴍE LEJ𝗔KE TᴏP 𝗕ED PE LIT𝗔KE 𝗖HᴏD DUᑎG𝗔 SU𝗔R KE PILLE 🤣🤣💋💋",
    "TERI ᴍ𝗔𝗔𝗔KE ᑎUDES GᴏᴏGLE PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 𝗕EHEᑎ KE L𝗔EWDE 👻🔥",
    "TERI ᴍ𝗔𝗔𝗔KE ᑎUDES GᴏᴏGLE PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 𝗕EHEᑎ KE L𝗔EWDE 👻🔥",
    "TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏD 𝗖HᴏDKE VIDEᴏ 𝗕𝗔ᑎ𝗔KE XᑎXX.𝗖ᴏᴍ PE ᑎEEL𝗔ᴍ K𝗔RDUᑎG𝗔 KUTTE KE PILLE 💦💋",
    "TERI ᴍ𝗔𝗔𝗔KI 𝗖HUD𝗔I Kᴏ PᴏRᑎHU𝗕.𝗖ᴏᴍ PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 SU𝗔R KE 𝗖HᴏDE 🤣💋💦",
    "𝗔𝗕E TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏDU R𝗔ᑎDIKE 𝗕𝗔𝗖HHE TEREKᴏ 𝗖H𝗔KKᴏ SE PILW𝗔VUᑎG𝗔 R𝗔ᑎDIKE 𝗕𝗔𝗖HHE 🤣🤣",
    "TERI ᴍ𝗔𝗔KI 𝗖HUTH F𝗔𝗔DKE R𝗔KDI𝗔 ᴍ𝗔𝗔KE LᴏDE J𝗔𝗔 𝗔𝗕𝗕 SILW𝗔LE 👄👄",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍER𝗔 LUᑎD K𝗔𝗔L𝗔",
    "TERI 𝗕EHEᑎ LETI ᴍERI LUᑎD 𝗕𝗔DE ᴍ𝗔STI SE TERI 𝗕EHEᑎ Kᴏ ᴍEᑎE 𝗖HᴏD D𝗔L𝗔 𝗕ᴏHᴏT S𝗔STE SE",
    "𝗕ETE TU 𝗕𝗔𝗔P SE LEG𝗔 P𝗔ᑎG𝗔 TERI ᴍ𝗔𝗔𝗔 Kᴏ 𝗖HᴏD DUᑎG𝗔 K𝗔RKE ᑎ𝗔ᑎG𝗔 💦💋",
    "H𝗔H𝗔H𝗔H ᴍERE 𝗕ETE 𝗔GLI 𝗕𝗔𝗔R 𝗔PᑎI ᴍ𝗔𝗔Kᴏ LEKE 𝗔𝗔Y𝗔 ᴍ𝗔TH K𝗔T ᴏR ᴍERE ᴍᴏTE LUᑎD SE 𝗖HUDW𝗔Y𝗔 ᴍ𝗔TH K𝗔R",
    "𝗖H𝗔L 𝗕ET𝗔 TUJHE ᴍ𝗔𝗔F KI𝗔 🤣 𝗔𝗕𝗕 𝗔PᑎI GF Kᴏ 𝗕HEJ",
    "SH𝗔R𝗔ᴍ K𝗔R TERI 𝗕EHEᑎ K𝗔 𝗕HᴏSD𝗔 KITᑎ𝗔 G𝗔𝗔LI𝗔 SUᑎW𝗔YEG𝗔 𝗔PᑎI ᴍ𝗔𝗔𝗔 𝗕EHEᑎ KE UPER",
    "𝗔𝗕E R𝗔ᑎDIKE 𝗕𝗔𝗖HHE 𝗔UK𝗔T ᑎHI HETᴏ 𝗔PᑎI R𝗔ᑎDI ᴍ𝗔𝗔Kᴏ LEKE 𝗔𝗔Y𝗔 ᴍ𝗔TH K𝗔R H𝗔H𝗔H𝗔H𝗔",
    "KIDZ ᴍ𝗔D𝗔R𝗖HᴏD TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏD 𝗖HᴏDKE TERR LIYE 𝗕H𝗔I DEDIY𝗔",
    "JUᑎGLE ᴍE ᑎ𝗔𝗖HT𝗔 HE ᴍᴏRE TERI ᴍ𝗔𝗔KI 𝗖HUD𝗔I DEKKE S𝗔𝗕 𝗕ᴏLTE ᴏᑎ𝗖E ᴍᴏRE ᴏᑎ𝗖E ᴍᴏRE 🤣🤣💦💋",
    "G𝗔LI G𝗔LI ᴍE REHT𝗔 HE S𝗔ᑎD TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏD D𝗔L𝗔 ᴏR 𝗕𝗔ᑎ𝗔 DI𝗔 R𝗔ᑎD 🤤🤣",
    "S𝗔𝗕 𝗕ᴏLTE ᴍUJHKᴏ P𝗔P𝗔 KYᴏUᑎKI ᴍEᑎE 𝗕𝗔ᑎ𝗔DI𝗔 TERI ᴍ𝗔𝗔Kᴏ PREGᑎEᑎT 🤣🤣",
    "SU𝗔R KE PILLE TERI ᴍ𝗔𝗔KI 𝗖HUTH ᴍE SU𝗔R K𝗔 LᴏUD𝗔 ᴏR TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍER𝗔 LᴏD𝗔",
    "𝗖H𝗔L 𝗖H𝗔L 𝗔PᑎI ᴍ𝗔𝗔KI 𝗖HU𝗖HIY𝗔 DIK𝗔",
    "H𝗔H𝗔H𝗔H𝗔 𝗕𝗔𝗖HHE TERI ᴍ𝗔𝗔𝗔Kᴏ 𝗖HᴏD DI𝗔 ᑎ𝗔ᑎG𝗔 K𝗔RKE",
    "TERI GF HE 𝗕𝗔DI SEXY USKᴏ PIL𝗔KE 𝗖HᴏᴏDEᑎGE PEPSI",
    "2 RUP𝗔Y KI PEPSI TERI ᴍUᴍᴍY S𝗔𝗕SE SEXY 💋💦",
    "TERI ᴍ𝗔𝗔Kᴏ 𝗖HEEᴍS SE 𝗖HUDW𝗔VUᑎG𝗔 ᴍ𝗔DER𝗖HᴏᴏD KE PILLE 💦🤣",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍUTHKE F𝗔R𝗔R HᴏJ𝗔VUᑎG𝗔 HUI HUI HUI",
    "SPEED L𝗔𝗔𝗔 TERI 𝗕EHEᑎ 𝗖HᴏDU R𝗔ᑎDIKE PILLE 💋💦🤣",
    "𝗔RE RE ᴍERE 𝗕ETE KYᴏUᑎ SPEED P𝗔K𝗔D ᑎ𝗔 P𝗔𝗔𝗔 R𝗔H𝗔 𝗔PᑎE 𝗕𝗔𝗔P K𝗔 H𝗔H𝗔H🤣🤣",
    "SUᑎ SUᑎ SU𝗔R KE PILLE JH𝗔ᑎTᴏ KE SᴏUD𝗔G𝗔R 𝗔PᑎI ᴍUᴍᴍY KI ᑎUDES 𝗕HEJ",
    "𝗔𝗕E SUᑎ LᴏDE TERI 𝗕EHEᑎ K𝗔 𝗕HᴏSD𝗔 F𝗔𝗔D DUᑎG𝗔",
    "TERI ᴍ𝗔𝗔Kᴏ KHULE 𝗕𝗔J𝗔R ᴍE 𝗖HᴏD D𝗔L𝗔 🤣🤣💋",
    "SHRᴍ KR",
    "ᴍERE LUᑎD KE 𝗕𝗔𝗔𝗔𝗔𝗔LLLLL",
    "KITᑎI GLIY𝗔 PDWYG𝗔 𝗔PᑎI ᴍ𝗔 𝗕HEᑎ Kᴏ",
    "RᑎDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "𝗔pᑎi g𝗔𝗔ᑎd ᴍeiᑎ ᴍuthi d𝗔𝗔l",
    "𝗔pᑎi luᑎd 𝗖hᴏᴏs",
    "𝗔pᑎi ᴍ𝗔 kᴏ j𝗔 𝗖hᴏᴏs",
    "𝗕heᑎ ke l𝗔ude",
    "𝗕heᑎ ke t𝗔kke",
    "𝗔𝗕l𝗔 TER𝗔 KH𝗔ᑎ D𝗔ᑎ 𝗖HᴏDᑎE KI 𝗕𝗔RIII",
    "𝗕ETE TERI ᴍ𝗔 S𝗕SE 𝗕DI R𝗔ᑎD",
    "TERI SEXY 𝗕𝗔HEᑎ KI 𝗖HUT ᴏP",
]